(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var A2=function(a){a.S("cardstatechange",g.vN(a)&&g.wN(a)?1:0)},Ova=function(a){var b=g.Oh(a);
a=g.Vh(a);return new g.zh(b.x,b.y,a.width,a.height)},Pva=function(a){return Math.pow(a,3)},Qva=function(a){return 3*a*a-2*a*a*a},B2=function(a,b){var c=g.Bo("use_default_events_client")?void 0:g.nr;
(0,g.y)(b,function(d){d={csn:a,ve:d.getAsJson(),eventType:4};var e={Ik:g.Bs(a),pk:a};"UNDEFINED_CSN"==a?g.Os("visualElementShown",d,e):c?g.Xp("visualElementShown",d,c,e):g.or("visualElementShown",d,e)})},C2=function(a,b){var c=g.Bo("use_default_events_client")?void 0:g.nr;
(0,g.y)(b,function(d){var e=void 0,f=(e=void 0===e?!1:e)?16:8;d={csn:a,ve:d.getAsJson(),eventType:f};e={Ik:g.Bs(a),pk:a,mG:e};"UNDEFINED_CSN"==a?g.Os("visualElementHidden",d,e):c?g.Xp("visualElementHidden",d,c,e):g.or("visualElementHidden",d,e)})},F2=function(a){a=g.Sa(a);
delete D2[a];g.Pb(D2)&&E2&&E2.stop()},Sva=function(){E2||(E2=new g.H(function(){Rva()},20));
var a=E2;a.isActive()||a.start()},Rva=function(){var a=(0,g.E)();
g.Bb(D2,function(b){Tva(b,a)});
g.Pb(D2)||Sva()},G2=function(a,b,c,d){g.Kn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.I=b;this.duration=c;this.F=d;this.coords=[];this.progress=this.G=0;this.C=null},Tva=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.C);a.C=b;Uva(a,a.progress);1==a.progress?(a.o=0,F2(a),a.zd(),a.In()):a.sb()&&a.yv()},Uva=function(a,b){g.Pa(a.F)&&(b=a.F(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.I[c]-a.A[c])*b+a.A[c]},Vva=function(a,b){g.Re.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.o},H2=function(a,b,c,d,e){G2.call(this,b,c,d,e);
this.element=a},I2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
H2.call(this,a,b,c,d,e)},J2=function(a){g.B.call(this);
this.u=a||window;this.o=[]},K2=function(a){return a.baseUrl||null},L2=function(a,b){return(0,g.De)((0,g.Lc)(a,b,void 0),function(c){return!!c})},Wva=function(a,b,c){function d(Ic){var Ob=Ic.hovercardButton;
if(!Ob)return null;Ob=Ob.subscribeButtonRenderer;if(!Ob)return null;var Ue=f(Ob.unsubscribedButtonText),bo=f(Ob.subscribedButtonText);if(Ob.subscribed){var co=f(Ob.subscriberCountWithUnsubscribeText);var eo=f(Ob.subscriberCountText)}else co=f(Ob.subscriberCountText),eo=f(Ob.subscriberCountWithSubscribeText);var Dj=null;return Ic.signinEndpoint&&(Dj=g.Jb(Ic,"signinEndpoint","webNavigationEndpointData","url"),!Dj)?null:Ue&&(bo||Dj)?{subscribed:Ob.subscribed,subscribeText:Ue,subscribeCount:co,unsubscribeText:bo,
unsubscribeCount:eo,enabled:Ob.enabled,signinUrl:Dj,classic:Ic.useClassicSubscribeButton}:null}
function e(Ic){if(Ic){var Ob=[],Ue=Ic.videoId;Ue&&Ob.push("v="+Ue);(Ue=Ic.playlistId)&&Ob.push("list="+Ue);(Ic=Ic.startTimeSeconds)&&Ob.push("t="+Ic);return"/watch?"+Ob.join("&")}}
function f(Ic){if(!Ic)return null;var Ob=Ic.simpleText;return Ob?Ob:Ic.runs?(0,g.Lc)(Ic.runs,function(Ue){return Ue.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,q=null,r=null,u=null,w=null,z=!1,A=null,C=null,F=null,G=null,R=null;if("VIDEO"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,r=f(b.videoDuration);else if("PLAYLIST"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==h){if(z=g.Jb(l,"browseEndpoint","browseId"))w=z,m="/channel/"+w;n=!1;q="new";(z=!!b.isSubscribe)?A=d(b):C=f(b.subscribersText)}else"WEBSITE"==
h?((F=g.Jb(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(R=f(b.additionalFeesText)),(n=g.Jb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Jb(b,"title","accessibility","accessibilityData","label");var aa=b.endpoint?b.endpoint.clickTrackingParams:null,cc="";if(b.metadata){var Wc=f(b.metadata);Wc&&(cc=Wc)}return{id:"element-"+c,type:h,title:f(b.title),metadata:cc,callToAction:f(b.callToAction),
Oy:b.image,iconUrl:F,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:r,playlistLength:u,channelId:w,subscribeButton:A,subscribersText:C,isSubscribe:z,targetUrl:m,BH:n,Dc:{itct:aa},bP:q,hm:a?a:null,FH:b.isPlaceholder,impressionUrls:L2(b.impressionUrls||[],K2),tH:L2(b.hovercardShowUrls||[],K2),clickUrls:L2(l.loggingUrls||[],K2),visualElement:g.us(b.trackingParams),productPrice:G,
additionalFeesText:R}},M2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=L2(a.impressionUrls||[],K2);a.trackingParams&&(c.visualElement=g.us(a.trackingParams));c.elements=L2(a.elements||[],function(d,e){return Wva(b,d,e)});
return c},N2=function(a){g.TN.call(this,a);
this.B=this.u=null;this.o={};this.G={};this.F=this.A=null;this.M=[];a=a.O();this.N=g.wy(a)||g.zy(a);this.R=!0;this.I=0;this.C=new g.ds(this);g.D(this,this.C);this.C.L(this.player,g.hz("creatorendscreen"),this.lI);this.C.L(this.player,"crx_creatorendscreen",this.mI);this.C.L(this.player,"resize",this.KA);this.C.L(window,"focus",this.VN);this.load();var b=g.xe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Oe(this,function(){g.Ce(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Xva=function(a){return a.player.getVideoData().jc?"current":a.N?"new":"current"},O2=function(a){return"creator-endscreen-editor"===a.player.O().playerStyle},P2=function(a,b,c){c=void 0===c?!0:c;
g.vQ(a.player.app,"creatorendscreen",void 0);a.A&&(a.A.dispose(),a.A=null,a.F.dispose(),a.F=null);for(var d in a.o)a.o[d].dispose();a.o={};a.G={};0<a.M.length&&(a.M.forEach(function(l){l.dispose()}),a.M.length=0);
a.I=0;if((a.u=b)&&b.elements){c&&Yva(a);c=[];d=new g.ez(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.O().o||(a.A=new g.U({D:"div",J:"ytp-ce-shadow"}),g.FN(a.player,a.A.element,4),a.F=new g.nO(a.A,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=Zva(a,e);a.o[e.id]=f;a.G[e.id]=e;g.FN(a.player,f.element,4);var h=new g.ez(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);$va(a,f,e)}g.BN(a.player,c);
a.KA()}},Yva=function(a){var b=g.ys(),c=g.As();
c&&b&&a.u.visualElement&&g.Us(c,b,a.u.visualElement)},Zva=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",X:["ytp-ce-element","ytp-ce-video"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-covering-image",P:Q2(b)},{D:"div",J:"ytp-ce-covering-shadow-top"},{D:"a",J:"ytp-ce-covering-overlay",P:{href:R2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",X:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Qn(b.title||"")},W:b.title},{D:"div",J:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.U(c);break;case "PLAYLIST":c={D:"div",X:["ytp-ce-element","ytp-ce-playlist"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-covering-image",P:Q2(b)},{D:"div",J:"ytp-ce-covering-shadow-top"},{D:"a",J:"ytp-ce-covering-overlay",P:{href:R2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",X:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Qn(b.title||"")},W:b.title},{D:"div",J:"ytp-ce-playlist-count",K:[{D:"div",
J:"ytp-ce-playlist-icon"},{D:"div",J:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.U(c);break;case "CHANNEL":c={D:"div",X:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",
K:[{D:"div",J:"ytp-ce-expanding-overlay-body",K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",X:["ytp-ce-channel-title","ytp-ce-link"],P:{href:R2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Qn(b.title||"")},W:b.title},b.subscribeButton?{D:"div",J:"ytp-ce-subscribe-container",K:[{D:"div",J:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",J:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{D:"div",X:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:Q2(b)}]};c=new g.U(c);var d=g.je(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.I(d,"ytp-ce-subscribe-button");if(a.player.O().o){var e=null;var f=b.Dc.itct}else e="endscreen",f=null;e=new g.vP(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.M.push(e)}break;case "WEBSITE":c={D:"div",X:["ytp-ce-element","ytp-ce-website"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",K:[{D:"div",J:"ytp-ce-expanding-overlay-body",
K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",J:"ytp-ce-website-title",P:{dir:g.Qn(b.title||"")},W:b.title},{D:"div",J:"ytp-ce-website-metadata",W:b.metadata},{D:"a",X:["ytp-ce-website-goto","ytp-ce-link"],P:{href:R2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:Q2(b)},{D:"div",J:"ytp-ce-expanding-icon",P:awa(b.iconUrl)}]};c=new g.U(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",J:"ytp-ce-merchandise-price-container",
K:[{D:"div",J:"ytp-ce-merchandise-price",W:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",J:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText})),c={D:"div",X:["ytp-ce-element","ytp-ce-merchandise"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",K:[{D:"div",
J:"ytp-ce-expanding-overlay-body",K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",J:"ytp-ce-merchandise-title",P:{dir:g.Qn(b.title||"")},W:b.title},c,{D:"div",J:"ytp-ce-merchandise-metadata",W:b.metadata},{D:"a",X:["ytp-ce-merchandise-goto","ytp-ce-link"],P:{href:R2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:Q2(b)},{D:"div",J:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",J:"ytp-ce-merchandise-invideo-cta",
W:b.callToAction}]}]},c=new g.U(c)}b.FH&&g.I(c.element,"ytp-ce-placeholder");return c},Q2=function(a){if(a.Oy)var b=a.Oy.thumbnails;
return awa(b?b[b.length-1].url:null)},awa=function(a){return a?{style:"background-image: url("+a+")"}:{}},$va=function(a,b,c){function d(){h(1)}
function e(){h(-1)}
b.na("mouseenter",(0,g.x)(a.Uu,a,b,c));b.na("mouseleave",(0,g.x)(a.Ev,a,b,c));a.player.O().o||b.na("click",(0,g.x)(function(l){g.I(l.element,"ytp-ce-element-hover")},a,b));
b.na("click",(0,g.x)(a.XB,a,c));b.na("keypress",(0,g.x)(a.XB,a,c));b.na("focus",(0,g.x)(function(l,m){this.Uu(l,m)},a,b,c));
b.na("blur",(0,g.x)(function(l,m){this.Ev(l,m)},a,b,c));
b.na("touchstart",(0,g.x)(a.Uu,a,b,c));var f=g.le("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.In(b.element,"ytp-ce-element-hover");g.In(b.element,"ytp-ce-force-expand")});
b.na("keydown",(0,g.x)(function(l,m){this.R=9==m.keyCode&&!m.shiftKey},a,b));
var h=(0,g.x)(function(l,m,n){this.I+=n;0<this.I?(g.I(l.element,"ytp-ce-force-expand"),S2(this,m.id,!0)):(g.In(l.element,"ytp-ce-force-expand"),g.In(l.element,"ytp-ce-element-hover"),S2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.na("blur",g.Ta(function(){"none"!=m.style.display&&a.R&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.le("ytp-sb-subscribe",b.element));c(g.le("ytp-sb-unsubscribe",b.element));b.na("focus",d);b.na("blur",e)},R2=function(a,b){var c=a.player.O();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.bz(c)+b}else return"";return b},S2=function(a,b,c){a.A&&(c?a.F.show():a.F.hide());
for(var d in a.o)d!=b&&g.J(a.o[d].element,"ytp-ce-element-shadow-show",c)},T2=function(a,b,c){function d(){f||(e++,e==b.length&&(h.stop(),c&&c()))}
if(!b||0==b.length||O2(a))c&&c();else{b=bwa(a,b);var e=0,f=!1,h=new g.H(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Ar(b[a],d)}},U2=function(a,b,c){T2(a,b.clickUrls,c);
(a=g.As())&&b.BH&&g.Vs(a,b.visualElement)},bwa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(cwa(b[e],c));return d},cwa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},dwa=function(a){return Array.isArray(a)&&a.length?a[0]:a},V2=function(a){return"string"===typeof a?a:""},W2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},fwa=function(a){var b=ewa;
if(null==a)return null;if(g.Oa(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},gwa=function(a){this.externalId=a},hwa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},X2=function(a){if(!a)return null;
var b=g.Ec(V2(a.value));b=g.Ac(b);if(!b)return null;var c=W2(a.target,iwa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new hwa(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Y2=function(a){return a.value?a.value:null},jwa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},ewa=function(a){if(!a)return null;
var b=W2(a.type,kwa),c=W2(a.trigger,lwa),d=dwa(a.url);d=X2(d?d:null);a=dwa(a.subscribeData);var e=a?a:null;e?(a=V2(e.external_user_id),e=V2(e.subscription_token),a=a&&e?new gwa(a):null):a=null;return b?new jwa(b,c,d,a):null},Z2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},mwa=function(a,b){return g.db(a.o,b,void 0)},nwa=function(a,b){this.merchant=a;
this.price=b},owa=function(a,b,c,d,e,f,h){this.o=a;
this.A=b;this.B=c;this.videoData=d;this.logger=e;this.H=f;this.u=h},pwa=function(a){this.o=a},a3=function(a){return a.customMessage?$2("div","iv-card-message",a.customMessage):""},b3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",J:"iv-card-image",P:{style:c},K:d}},c3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push($2("li","",d))},a);
return{D:"ul",J:"iv-card-meta-info",K:c}},$2=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Qn(c);return{D:a,P:b,W:c}},qwa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Wo&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Wo+");");c.dir=g.Qn(a.customMessage);var d=[{D:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",J:"iv-card-link-icon"}));return{D:"div",X:b,P:c,K:d}},d3=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.o(e,d,c.id,c.Dc,c.Yd.click,5)},a)},rwa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},swa=function(a,b){return b?b:rwa(a)?"current":"new"},e3=function(a,b){g.B.call(this);
var c=this;this.element=a;this.context=b;this.Aa=!1;this.sa=new Map;this.oa=new Map;this.context.H.addEventListener(g.hz("annotations_module"),function(d){(d=c.sa.get(d))&&d.apply(c)});
this.context.H.addEventListener("crx_annotations_module",function(d){(d=c.oa.get(d))&&d.apply(c)})},twa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},f3=function(a,b,c){return{Vz:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
QD:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Xr:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},i3=function(a,b,c){e3.call(this,b,c);
var d=this;this.u=a;this.fa=this.Ia=this.C=this.Ga=!1;this.ga=null;this.aa=new g.H(g.La,c.B.ib?4E3:3E3);g.D(this,this.aa);this.za=new g.H(g.La);g.D(this,this.za);this.Z=new pwa((0,g.x)(this.Ml,this),(0,g.x)(this.rq,this));this.T=new g.U({D:"div",J:"iv-drawer",P:{id:"iv-drawer"},K:[{D:"div",J:"iv-drawer-header",P:{"aria-role":"heading"},K:[{D:"span",J:"iv-drawer-header-text"},{D:"button",X:["iv-drawer-close-button","ytp-button"],P:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",J:"iv-drawer-content"}]});
g.D(this,this.T);this.F=this.T.element;this.ua=new g.nO(this.T,330);g.D(this,this.ua);this.Fa=g.le("iv-drawer-header-text",this.F);this.B=g.le("iv-drawer-content",this.F);this.A=[];this.Ea=this.R=this.G=this.ha=this.o=null;this.U=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Ia&&g3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ia=d.C)&&h3(d)});
this.N=this.I=this.ba=null;this.M=0},uwa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){g3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){h3(a)});
var c=b.data.headerText;g.Ge(a.Fa,c);a.R&&a.R.setAttribute("title",c);a.ba=g.us(b.data.trackingParams);a.N=g.us(b.data.closeTrackingParams);a.I=g.us(b.data.iconTrackingParams)},vwa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.M;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"simple",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Dc:j3(a,c,b,d),sponsored:!1,Yd:f3(d,e,d.command),bh:d.trackingParams?g.us(d.trackingParams):null,sf:e.trackingParams?
g.us(e.trackingParams):null,le:f&&f.trackingParams?g.us(f.trackingParams):null,imageUrl:k3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.S(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Wo:null,title:d.title?g.S(d.title):"",customMessage:d.callToAction?g.S(d.callToAction):"",url:d.command.urlEndpoint.url?X2({pause_on_navigation:!a.context.videoData.ya,target:"new",value:d.command.urlEndpoint.url}):null};l3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"collaborator",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Dc:j3(a,c,b,d),sponsored:!1,Yd:f3(d,e,d.endpoint),bh:d.trackingParams?g.us(d.trackingParams):null,sf:e.trackingParams?g.us(e.trackingParams):null,le:f&&f.trackingParams?
g.us(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.S(d.customText):null,VC:k3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.S(d.channelName):"",metaInfo:[d.subscriberCountText?g.S(d.subscriberCountText):""],url:X2({pause_on_navigation:!a.context.videoData.ya,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};l3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"playlist",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Dc:j3(a,c,b,d),sponsored:!1,Yd:f3(d,e,d.action),bh:d.trackingParams?g.us(d.trackingParams):null,sf:e.trackingParams?g.us(e.trackingParams):null,le:f&&f.trackingParams?g.us(f.trackingParams):
null,oo:k3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.S(d.customMessage):null,playlistVideoCount:g.S(d.playlistVideoCount),title:d.playlistTitle?g.S(d.playlistTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.videoCountText?g.S(d.videoCountText):""],url:X2({pause_on_navigation:!a.context.videoData.ya,target:"new",value:twa(d.action)})};l3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.M,type:"video",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Dc:j3(a,c,b,d),sponsored:!1,Yd:f3(d,e,d.action),bh:d.trackingParams?g.us(d.trackingParams):null,sf:e.trackingParams?g.us(e.trackingParams):null,le:f&&f.trackingParams?g.us(f.trackingParams):null,oo:k3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.S(d.lengthString):null,customMessage:d.customMessage?g.S(d.customMessage):null,title:d.videoTitle?g.S(d.videoTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.viewCountText?g.S(d.viewCountText):""],isLiveNow:!!d.badge,url:X2({pause_on_navigation:!a.context.videoData.ya,target:"new",value:twa(d.action)})};l3(a,c)}a.M++},k3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},j3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},xwa=function(a,b){var c=wwa(a,b);
c&&(c==a.o&&(a.o=null),a.u.removeCueRange(c.card.id),g.Ce(c.jt),g.lb(a.A,c),a.Zo(),m3(a))},g3=function(a,b,c){if(!a.C){a.ua.show();
a.ha=new g.H(function(){g.I(a.context.H.getRootNode(),g.fM.IV_DRAWER_OPEN)},0);
a.ha.start();a.ga=g.hp(a.B,"mousewheel",(0,g.x)(a.hM,a));a.C=!0;var d=g.As();d&&a.ba&&a.N&&B2(d,[a.ba,a.N]);var e={TRIGGER_TYPE:b};(0,g.y)(a.A,function(f){f.uA||(f.uA=!0,ywa(a.context.logger,f.card.Yd.Vz,e));d&&B2(d,[f.card.bh])});
A2(a.u);c&&(a.G=new g.H(function(){a.wa=a.R;a.Ea.focus()},330),a.G.start())}},h3=function(a){a.C&&(a.ua.hide(),g.ip(a.ga),a.ga=null,g.In(a.context.H.getRootNode(),g.fM.IV_DRAWER_OPEN),a.C=!1,A2(a.u),a.G&&a.G.stop(),a.G=new g.H(function(){a.wa&&(a.wa.focus(),a.wa=null)},330),a.G.start())},zwa=function(a){var b=g.le("iv-drawer-close-button",a.F);
a.context.o.na(b,"click",a.RF,a);a.context.o.na(a.B,"touchend",function(){a.aa.start()});
a.context.o.na(a.B,"scroll",a.iG,a);a.context.u.subscribe("onHideControls",function(){a.fa=!0});
a.context.u.subscribe("onShowControls",function(){a.fa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.fa=g.Gn(a.u.getRootNode(),"ytp-autohide")});
a.U.push(g.So("iv-button-shown",a.KH,a));a.U.push(g.So("iv-button-hidden",a.JH,a));a.U.push(g.So("iv-teaser-shown",a.NH,a));a.U.push(g.So("iv-teaser-hidden",a.MH,a));a.U.push(g.So("iv-teaser-clicked",a.LH,a))},l3=function(a,b){a.Ga||(g.Hn(a.xa(),[g.fM.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]),g.FN(a.u,a.F,5),zwa(a),a.R=g.le("ytp-cards-button",a.u.getRootNode()),a.Ea=g.le("iv-drawer-close-button",a.F),a.Ga=!0);xwa(a,b.id);var c=Awa(a,b);if(c){var d={card:b,jt:c.element,uA:!1},e=Bwa(a,d);g.sb(a.A,e,0,d);c.ca(a.B,e);a.Zo();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Ta(a.MO,d)):(c=1E3*a.context.H.getCurrentTime(),5E3>c&&c>b.startMs&&a.DD(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Ta(a.DD,d)),m3(a))}},Awa=function(a,b){switch(b.type){case "simple":var c=
a.Z;
var d=b.displayDomain?{D:"div",J:"iv-card-image-text",W:b.displayDomain}:"";var e=qwa(b);d={D:"div",X:["iv-card"],K:[{D:"a",J:"iv-click-target",P:{href:Y2(b.url)},K:[b3(b.imageUrl,d),{D:"div",J:"iv-card-content",K:[$2("h2",void 0,b.title),e]}]}]};d=new g.U(d);d3(c,g.ke("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.Z,d={D:"div",X:["iv-card","iv-card-channel"],K:[{D:"a",X:["iv-click-target"],P:{href:Y2(b.url),"data-ytid":b.channelId},K:[b3(b.VC),{D:"div",J:"iv-card-content",
K:[a3(b),{D:"h2",J:"iv-card-primary-link",W:b.title},c3(c,b)]}]}]},d=new g.U(d),d3(c,g.ke("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.Z,d={D:"div",X:["iv-card","iv-card-playlist"],K:[{D:"a",J:"iv-click-target",P:{href:Y2(b.url)},K:[b3(b.oo,{D:"div",J:"iv-card-image-overlay",K:[{D:"span",J:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{D:"div",J:"iv-card-content",K:[a3(b),$2("h2","iv-card-primary-link",b.title),c3(c,b)]}]}]},d=new g.U(d),d3(c,g.ke("iv-click-target",
d.element),b,b.url),d;case "productListing":c=a.Z;var f=!g.ib(b.offers);d=["iv-card"];e="";var h=qwa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],h=[],f.price&&h.push({D:"div",J:"iv-card-offer-price",W:f.price}),f.merchant&&h.push({D:"div",J:"iv-card-offer-merchant",W:f.merchant}),h={D:"div",K:h});d={D:"div",X:d,P:{tabindex:"0"},K:[{D:"a",X:["iv-card-image","iv-click-target"],P:{style:"background-image: url("+b.imageUrl+");",href:Y2(b.url),"aria-hidden":"true",tabindex:"-1"}},
{D:"div",J:"iv-card-content",K:[b.sponsored?{D:"div",J:"iv-card-sponsored",K:["Sponsored",{D:"div",J:"iv-ad-info-container",K:[{D:"div",J:"iv-ad-info",W:"{{adInfo}}"},{D:"div",J:"iv-ad-info-icon-container",K:[{D:"div",J:"iv-ad-info-icon"},{D:"div",J:"iv-ad-info-callout"}]}]}]}:"",{D:"a",J:"iv-click-target",P:{href:Y2(b.url)},K:[$2("h2",e,b.title),h]}]}]};d=new g.U(d);e=g.xe("span");g.Ge(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Cb(e,"adInfo");d3(c,g.ke("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.Z,d=b.isLiveNow?{D:"span",X:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={D:"div",X:["iv-card","iv-card-video"],K:[{D:"a",J:"iv-click-target",P:{href:Y2(b.url)},K:[b3(b.oo,b.videoDuration?{D:"span",J:"iv-card-video-duration",W:b.videoDuration}:""),{D:"div",J:"iv-card-content",K:[a3(b),$2("h2","iv-card-primary-link",b.title),c3(c,b),d]}]}]},d=new g.U(d),d3(c,g.ke("iv-click-target",d.element),b,b.url),
d}return null},Bwa=function(a,b){if(0==a.A.length)return 0;
var c=g.eb(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},Cwa=function(a){return a.o?"productListing"==a.o.card.type:(0,g.Bi)(a.A,function(b){return"productListing"==b.card.type})},m3=function(a){g.J(a.u.getRootNode(),"ytp-cards-shopping-active",Cwa(a))},Dwa=function(a,b){if(a.T.Ma()){var c=new G2([0,
a.B.scrollTop],[0,b.jt.offsetTop],600,Qva);a.context.A.na(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.A.na(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.eM(a.T,!0),a.B.scrollTop=b.jt.offsetTop,g.eM(a.T,!1)},n3=function(a){return a.o&&a.o.card?a.o.card:a.A[0]&&a.A[0].card?a.A[0].card:null},wwa=function(a,b){return g.db(a.A,function(c){return c.card.id==b})},Ewa=function(a){this.o=a},ywa=function(a,b,c){b&&(c?o3(a,(0,g.Lc)(b,g.Ta(function(d,e){return g.mn(e,d)},c))):o3(a,b))},o3=function(a,b,c,d){var e=1,f=-1;
if(c){var h=!1;var l=function(){e--;e||h||(clearTimeout(f),h=!0,c())};
f=setTimeout(function(){h=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.Ar(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},p3=function(a,b,c){e3.call(this,a,b);
this.annotation=c;this.isActive=!1},Fwa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},q3=function(a,b,c){p3.call(this,a,b,c);
this.u=null;this.G=!1;this.A=null;this.B=!1;this.o=this.F=this.C=null},Gwa=function(a,b){var c=void 0===c?0:c;
var d=Ova(b).width;g.Kh(b,d);c=new I2(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Pva);g.D(a,c);a.context.A.na(c,"begin",function(){g.Wh(b,!0)});
c.play()},Jwa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
X:["iv-branding-context-name"],W:b.channel_name}),d=a.createElement({D:"div",X:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.o=new g.vP(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.H),a.o.ca(d));var f=a.createElement({D:"div",X:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",X:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Wh(h,!1);var l=a.createElement({D:"div",X:["branding-context-container-outer"]});l.appendChild(h);g.Ch(l,"right",b.image_width+"px");a.xa().appendChild(l);a.A=new g.H(function(){Hwa(a,h,l)},500);
g.D(a,a.A);a.context.o.na(a.xa(),"mouseover",function(){Iwa(a,h,l,f,b.image_height)});
a.context.o.na(a.xa(),"mouseout",function(){a.A.start()})}},Iwa=function(a,b,c,d,e){a.A.stop();
if(!a.B){var f=g.Vh(b);a.o||(g.Th(b,f.width),g.Th(c,f.width));g.Ch(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Ch(d,"right","1px");a.B=!0;g.Wh(b,!0);a.C=new g.H(function(){g.I(this.xa(),"iv-branding-active")},0,a);
a.C.start()}},Hwa=function(a,b,c){g.In(a.xa(),"iv-branding-active");
a.F=new g.H(function(){g.Wh(b,!1);a.o||g.Th(c,0)},250);
a.F.start();a.B=!1},r3=function(a,b,c){p3.call(this,a,b,c);
var d=this;this.I=this.isCollapsed=this.M=!1;this.F=5E3;this.u=this.A=this.o=this.B=null;this.G=this.createElement({D:"div",X:["iv-promo-contents"]});this.C=new g.H(function(){d.o.setAttribute("aria-hidden","true");g.Wh(d.A,!1);g.Wh(d.u,!0)},700,this);
g.D(this,this.C)},Kwa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.F=b.collapsedelay_ms||a.F;var d=["iv-promo","iv-promo-inactive"];a.xa().setAttribute("aria-hidden","true");a.xa().setAttribute("aria-label","Promotion");a.xa().tabIndex=0;var e=a.annotation.zc(),f=b.image_url;if(f){var h=a.createElement({D:"div",X:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",P:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({D:"span",J:"iv-promo-video-duration",W:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",J:"iv-promo-playlist-length",W:b.playlist_length.toString()}),h.appendChild(f));e&&a.Ml(h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",J:"iv-promo-txt"}),g.fd(f,Y2(e)),a.o=f):a.o=a.createElement({D:"div",J:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",K:[{D:"strong",W:b.text_line_1}]});
var m=a.createElement({D:"p",K:[{D:"span",J:"iv-promo-link",W:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",X:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",X:["iv-button","iv-promo-button"],K:[{D:"span",J:"iv-button-content",W:f}]});var q=a.createElement({D:"div",J:"iv-promo-button-container"});q.appendChild(f);e&&a.Ml(a.xa(),e,a.annotation.id,b.session_data,void 0,c)}g.I(a.o,"iv-click-target");e&&
a.Ml(a.o,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",K:[{D:"span",W:b.text_line_1}]}),m=a.createElement({D:"p",K:[{D:"strong",W:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",X:["yt-badge","iv-promo-badge-live"],W:"LIVE NOW"})),g.I(a.o,"iv-click-target"),e&&a.Ml(a.o,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.G.appendChild(a.o);q&&a.G.appendChild(q);c=a.createElement({D:"div",
J:"iv-promo-actions"});a.u=a.createElement({D:"button",X:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.o.na(a.u,"click",function(r){s3(a,5E3,r)});
c.appendChild(a.u);g.Wh(a.u,!1);a.context.o.na(a.xa(),"mouseover",a.bH,a);a.context.o.na(a.xa(),"mouseout",a.aH,a);a.context.o.na(a.xa(),"touchend",function(r){s3(a,5E3,r)});
a.A=a.createElement({D:"button",X:["iv-promo-close","ytp-button"]});a.A.title="Close";a.context.o.na(a.A,"click","cta"===a.annotation.style&&b.text_line_3?a.UG:a.TG,a);c.appendChild(a.A);g.Hn(a.xa(),d);h&&(a.xa().appendChild(h),n&&h.appendChild(n));a.xa().appendChild(a.G);a.xa().appendChild(c)},s3=function(a,b,c){c.stopPropagation();
Lwa(a);Mwa(a,b);a.o.focus()},Nwa=function(a){a.isCollapsed||a.I||a.B||(g.I(a.xa(),"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},Lwa=function(a){a.C.stop();
a.isCollapsed&&(g.Jn(a.xa(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.Wh(a.u,!1),g.Wh(a.A,!0))},Mwa=function(a,b){a.B||(a.B=g.dg(function(){t3(this);
Nwa(this)},b,a))},t3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},u3=function(a){g.TN.call(this,a);
this.N=!1;this.M=0;this.G={};this.Z=new Ewa(a);this.C=new g.ds(this);g.D(this,this.C);this.F=this.A=null;this.C.L(this.player,"onVideoAreaChange",(0,g.x)(this.S,this,"onVideoAreaChange"));this.C.L(this.player,"onHideControls",(0,g.x)(this.S,this,"onHideControls"));this.C.L(this.player,"onShowControls",(0,g.x)(this.S,this,"onShowControls"));this.C.L(this.player,"resize",(0,g.x)(this.S,this,"resize"));this.C.L(this.player,"presentingplayerstatechange",(0,g.x)(this.S,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.jI,this);this.subscribe("resize",this.qr,this);this.player.O().M.subscribe("vast_info_card_add",this.GC,this);this.U=new g.ds(this);g.D(this,this.U);this.T=g.we("DIV","video-custom-annotations");this.u=new g.U({D:"div",X:["ytp-player-content","ytp-iv-player-content"]});g.D(this,this.u);g.FN(this.player,this.u.element,4);this.u.hide();this.B=new g.U({D:"div",X:["ytp-iv-video-content"]});g.D(this,this.B);g.ze(this.B.element,g.we("DIV","video-annotations",
this.T));this.I=this.o=null;this.R=[];Owa(this)&&this.load();var b=g.xe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Oe(this,function(){g.Ce(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Pwa=function(){var a=g.we("DIV",["annotation",
"annotation-type-custom"]);g.Wh(a,!1);return a},Qwa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},Owa=function(a){var b=a.player.O();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.wE||b.M.get(a.videoId)||g.XB(a)||g.YB(a)?!0:!1},Rwa=function(a,b){var c=!b.isCued()&&!g.T(b,1024);
g.eM(a.u,c);g.eM(a.B,c)},Swa=function(a,b,c){a.N=!0;
a.F=g.vq(b,c)},Twa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Qa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Twa(a,e))}return c},Uwa=function(a,b,c){return!(a.loaded&&a.M==b&&a.player.getVideoData().videoId==
c)},Xwa=function(a){var b=a.player.getVideoData();
if(b.af){var c=a.player.O().M.get(b.videoId);if(c){var d={format:"XML",We:{},method:"POST",withCredentials:!0};d.zd=(0,g.x)(function(e,f,h){Uwa(this,e,f)||(e=g.pq(h)&&h.responseXML?h.responseXML:null)&&v3(this,e)},a,a.M,b.videoId);
g.xp()&&(d.zd=Vwa(a,d.zd));d.Fb={ic_only:"1"};Wwa(d,c);a.N=!0;g.vq(b.af,d)}}},Wwa=function(a,b){a.method="POST";
a.Fb=a.Fb||{};b.gp&&(a.Fb.ic_coll=b.gp);b.hp&&(a.Fb.ic_xml=b.hp);b.so&&(a.Fb.ic_track=b.so)},Ywa=function(a){var b=new g.U({D:"div"});
g.Wh(b.element,!1);var c=new i3(a.player,b.element,w3(a));g.D(c,b);b.ca(a.u.element);c.bo();return c},w3=function(a){if(!a.I){var b=new J2(a);
g.D(a,b);var c=new g.z1(a);g.D(a,c);a.I=new owa(b,c,a.player.O(),a.player.getVideoData(),a.Z,a.player,a.Ri)}return a.I},v3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.As();if(e){var f=g.ys();f&&g.Ps(g.Bo("use_default_events_client")?void 0:g.nr,e,f,[g.us(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=Twa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=W2(h.type,Zwa),r=W2(h.style,$wa),u=V2(h.data),w=0!=u.length?JSON.parse(u):{},z=fwa(h.action);f=n&&q?new Z2(n,q,r,z,w):null}else f=null}catch(R){}if(f){a:{switch(f.type){case "branding":case "promotion":h=
!0;break a}h=!1}if(h){h=a;m=f;var A=Pwa(),C=null;switch(m.type){case "branding":if(h.player.O().Ia)break;h.u.element.appendChild(A);C=new q3(A,w3(h),m);break;case "promotion":g.FN(h.player,A,4),C=new r3(A,w3(h),m)}C&&C.bo();if(h=C)g.D(a,h),a.G[f.id]=h}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=Ywa(a),g.D(a,a.o));if("card"==f.type){if(c=a.o,C=f&&f.data&&f.data.card_type)switch(h=f.data.tracking||{},h={Vz:h.impression,click:h.click,close:h.close,QD:h.teaser_impression,Xr:h.teaser_click},m=
f.data.tracking_params||{},A=null,C){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Dc:f.data.session_data||{},sponsored:f.data.sponsored||!1,Yd:h,bh:m.card?g.us(m.card):null,sf:m.teaser?g.us(m.teaser):null,le:m.icon?g.us(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,VC:f.data.image_url,
title:f.data.title,metaInfo:f.data.meta_info,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};l3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Dc:f.data.session_data||{},sponsored:f.data.sponsored||!1,Yd:h,bh:m.card?g.us(m.card):null,sf:m.teaser?g.us(m.teaser):null,le:m.icon?
g.us(m.icon):null,oo:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};l3(c,f);break;case "productListing":f.data.signin_url&&(A=X2({target:"current",value:f.data.signin_url}));C=[];for(var F=f.data.offers||[],G=0;G<F.length;G++)C.push(new nwa(g.nd(F[G].merchant),g.nd(F[G].price)));
f={bU:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Dc:f.data.session_data||{},sponsored:f.data.sponsored||!1,Yd:h,bh:m.card?g.us(m.card):null,sf:m.teaser?g.us(m.teaser):null,le:m.icon?g.us(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Wo:f.data.button_icon_url?f.data.button_icon_url:
null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),zU:A,yU:f.data.signin_title?f.data.signin_title:null,xU:f.data.signin_message?f.data.signin_message:null,offers:C};l3(c,f);break;case "simple":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||
!1,Dc:f.data.session_data||{},sponsored:f.data.sponsored||!1,Yd:h,bh:m.card?g.us(m.card):null,sf:m.teaser?g.us(m.teaser):null,le:m.icon?g.us(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Wo:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};
l3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Dc:f.data.session_data||{},sponsored:f.data.sponsored||!1,Yd:h,bh:m.card?g.us(m.card):null,sf:m.teaser?g.us(m.teaser):null,le:m.icon?g.us(m.icon):null,oo:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,
metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},l3(c,f)}}else uwa(a.o,f);c=!0}}}c&&(A2(a.player),a.qr())},axa=function(a,b){var c=!1;
a.o||(a.o=Ywa(a),g.D(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())vwa(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.S(b.headerText):"",g.Ge(c.Fa,d),c.R&&c.R.setAttribute("title",d),c.ba=b.trackingParams?g.us(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.us(b.closeButton.infoCardIconRenderer.trackingParams):null,c.I=b.icon.infoCardIconRenderer.trackingParams?g.us(b.icon.infoCardIconRenderer.trackingParams):null,A2(a.player),a.qr())},
bxa=function(a,b,c,d,e){if(!a.player.O().Ia){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new jwa("openUrl","click",new hwa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.S(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.S(b.subscriberCountText))):(b.subscriberCountText&&(e=g.S(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.S(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.S(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.S(b.subscribedButtonText),unsubscribeCount:h,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new Z2(c,"branding","branding",f,d);d=Pwa();a.u.element.appendChild(d);f=new q3(d,w3(a),f);f.bo();g.D(f,f);a.G[c]=f}},Vwa=function(a,b){return(0,g.x)(function(){if(!this.ia()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Ta.apply(window,c);this.R.push(g.vp(b))}},a)},D2={},E2=null;g.Va(G2,g.Kn);g.k=G2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.sb())return!1;F2(this);this.startTime=a=(0,g.E)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.lr();this.bf("play");-1==this.o&&this.bf("resume");this.o=1;var b=g.Sa(this);b in D2||(D2[b]=this);Sva();Tva(this,a);return!0};
g.k.stop=function(a){F2(this);this.o=0;a&&(this.progress=1);Uva(this,this.progress);this.bf("stop");this.In()};
g.k.pause=function(){this.sb()&&(F2(this),this.o=-1,this.bf("pause"))};
g.k.Y=function(){0==this.o||this.stop(!1);this.bf("destroy");G2.wc.Y.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.yv=function(){this.bf("animate")};
g.k.bf=function(a){this.dispatchEvent(new Vva(a,this))};
g.Va(Vva,g.Re);g.Va(H2,G2);H2.prototype.B=g.La;H2.prototype.yv=function(){this.B();H2.wc.yv.call(this)};
H2.prototype.In=function(){this.B();H2.wc.In.call(this)};
H2.prototype.lr=function(){this.B();H2.wc.lr.call(this)};
g.Va(I2,H2);I2.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.t(J2,g.B);J2.prototype.na=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.hp(a,b,c);this.o.push(a);return a};
J2.prototype.Mu=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.qp(a,b,c);this.o.push(a);return a};
J2.prototype.ob=function(a){g.ip(a);g.lb(this.o,a)};
J2.prototype.Y=function(){g.ip(this.o);this.o.length=0;g.B.prototype.Y.call(this)};g.t(N2,g.TN);g.k=N2.prototype;g.k.load=function(){g.TN.prototype.load.call(this);if(!O2(this)){var a=g.WB(this.player.getVideoData());if(a)a=M2(a,Xva(this)),P2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.B&&this.B.abort();a={method:"POST",zd:(0,g.x)(this.yL,this,a),We:{v:a},withCredentials:!0};this.N&&(a.We.ptype="embedded");var c=this.player.getVideoData().wp;c&&(a.Fb={ad_tracking:c});if(b=g.VB(b))if(b=g.Ec(b),b=g.Ac(b))this.B=g.vq(b,a)}}};
g.k.unload=function(){P2(this,null);this.B&&(this.B.abort(),this.B=null);g.TN.prototype.unload.call(this)};
g.k.cd=function(a,b){if(!O2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=M2(b,"new");P2(this,c);return!0}return null};
g.k.getOptions=function(){return O2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.yL=function(a,b){var c=this.B=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=M2(c,Xva(this)))}P2(this,c)};
g.k.KA=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<cxa.length;f++){var h=Math.abs(b.width-cxa[f]);if(-1==e||d>=h)e=f,d=h}d=dxa[e];this.A&&g.Ch(this.A.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Uh(e.element,Math.round(h.width*a.width),f);g.Kh(e.element,m,n);g.Jn(e.element,exa);m=h.left+h.width/2;h=h.top+l/2;g.I(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Jn(e.element,dxa);g.I(e.element,d);(e=g.je(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Ch(e,"height",f+"px")}}}}};
g.k.lI=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())T2(this,this.u.impressionUrls),(a=g.As())&&this.u.visualElement&&g.Qs(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.I(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.I(b,"ytp-ce-shown");T2(this,c.impressionUrls);(b=g.As())&&g.Qs(b,c.visualElement);this.player.O().A&&this.player.ra("endscreenelementshown",a)}};
g.k.mI=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.In(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.In(b,"ytp-ce-shown");this.player.O().A&&this.player.ra("endscreenelementhidden",a)}};
g.k.VN=function(a){var b=this;a.target===window&&(new g.H(function(){for(var c in b.o)g.Jn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.XB=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Gn(c,"ytp-ce-element");){g.Gn(c,"subscribe-label")&&U2(this,a);if(g.Gn(c,"ytp-ce-channel-subscribe"))return;c=g.Ee(c)}if(!c||g.Gn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Ev(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.bP?(U2(this,a),this.CD(),this.player.pauseVideo(),c=g.Ec(R2(this,a.targetUrl)),c=g.Ac(c),g.uO(c,void 0,a.Dc)):(c=this.player.getVideoData().jc,
c=(0,g.x)(this.UO,this,c,R2(this,a.targetUrl),a.Dc),c=(0,g.x)(this.CD,this,c),U2(this,a,c))}}};
g.k.UO=function(a,b,c){var d=g.dq(b);a&&d&&(d.v||d.list)?g.yU(this.player.app,d.v,c,d.list,!1,void 0):g.tO(b,c)};
g.k.Uu=function(a,b){g.Gn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.I(a.element,"ytp-ce-element-hover"):this.player.O().o?(new g.H(function(){g.I(a.element,"ytp-ce-element-hover")},200)).start():g.I(a.element,"ytp-ce-element-hover"),T2(this,b.tH),S2(this,b.id,!0))};
g.k.Ev=function(a,b){g.In(a.element,"ytp-ce-element-hover");g.In(a.element,"ytp-ce-force-expand");S2(this,b.id,!1)};
g.k.CD=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var cxa=[346,426,470,506,570,640,853,1280,1920],dxa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),exa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var iwa={LQ:"current",iS:"new"};var kwa={CLOSE:"close",lS:"openUrl",qF:"subscribe"},lwa={BQ:"click",CLOSE:"close",tR:"hidden",WS:"rollOut",XS:"rollOver",dT:"shown"};Z2.prototype.zc=function(){var a=mwa(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
var $wa={jQ:"anchored",ME:"branding",CHANNEL:"channel",KQ:"cta",wR:"highlightText",LR:"label",PLAYLIST:"playlist",IS:"popup",jT:"speech",qF:"subscribe",vT:"title",VIDEO:"video",IT:"website"},Zwa={ME:"branding",tQ:"card",QQ:"drawer",vR:"highlight",WR:"marker",NS:"promotion",TEXT:"text",KT:"widget"};g.t(e3,g.B);g.k=e3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.ez(a,b,{id:c});a.namespace="annotations_module";d&&this.sa.set(a,d);e&&this.oa.set(a,e);g.BN(this.context.H,[a])};
g.k.bo=function(){this.context.u.subscribe("resize",this.Zo,this)};
g.k.xa=function(){return this.element};
g.k.Ml=function(a,b,c,d,e,f){var h=this;this.context.o.na(a,"click",function(){h.rq(b,c,d,e||[],f||0)});
this.context.o.na(a,"touchstart",function(){h.Aa=!1});
this.context.o.na(a,"touchmove",function(){h.Aa=!0})};
g.k.rq=function(a,b,c,d,e,f){if(this.Aa)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Ce(this.xa())};
g.k.Zo=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=Y2(a);if(f){var h=swa(f,a.target),l=function(){a.o&&e.context.H.pauseVideo();var m=e.context.videoData.jc||!1,n=g.dq(f||"");m&&n&&(n.v||n.list)?g.yU(e.context.H.app,n.v,b,n.list,!1,void 0):g.uO(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);o3(this.context.logger,c,l,d);rwa(f)||(c=g.As(),d=b.itct,c&&d&&g.Vs(c,g.us(d)))}};
g.k.Y=function(){this.sa.clear();this.oa.clear();g.B.prototype.Y.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.D(this,a);return a.element};g.t(i3,e3);g.k=i3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.A.length)(a=this.u.getRootNode())?(a=g.Vh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Zo=function(){var a=this.isAvailable();g.Wh(this.xa(),a);g.J(this.context.H.getRootNode(),g.fM.IV_DRAWER_ENABLED,a);A2(this.u)};
g.k.destroy=function(){var a=g.uN(g.jN(this.u));a&&a.Su(!1,void 0);try{this.u.getRootNode().removeChild(this.F)}catch(b){}g.To(this.U);g.ip(this.ga);this.ha&&this.ha.dispose();this.G&&this.G.dispose();e3.prototype.destroy.call(this)};
g.k.hM=function(a){this.aa.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.k.DD=function(a){if(!g.Gn(this.u.getRootNode(),"ytp-cards-teaser-shown")){if(this.o!=a){var b=g.As(),c=this.o?this.o.card.le:this.I;b&&c&&C2(b,[c]);this.o=a;m3(this)}if(b="none"!=this.xa().style.display)2==this.context.H.getPresentingPlayerType()?b=1==this.context.H.getAdState():(b=this.context.H.getPlayerState(),c=0==b&&0===this.context.H.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.uN(g.jN(this.u)))&&c.Su(!0,
b));this.za.isActive()||((!this.C||!this.aa.isActive()&&this.fa)&&Dwa(this,a),this.za.start(910+a.card.teaserDurationMs))}};
g.k.MO=function(a){this.C||(this.o=a,m3(this),Dwa(this,a),g3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.k.RF=function(){if(this.C){o3(this.context.logger,n3(this).Yd.close);var a=g.As();a&&this.N&&g.Vs(a,this.N);h3(this)}};
g.k.iG=function(){g.J(this.F,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.KH=function(){var a=g.As(),b=n3(this);b=b?b.le:this.I;a&&b&&B2(a,[b])};
g.k.JH=function(){var a=g.As(),b=n3(this);b=b?b.le:this.I;a&&b&&C2(a,[b])};
g.k.NH=function(){var a=n3(this);o3(this.context.logger,a.Yd.QD);var b=g.As();b&&a&&B2(b,[a.sf,a.le])};
g.k.MH=function(){var a=g.As(),b=n3(this);a&&b&&C2(a,[b.sf])};
g.k.LH=function(a){var b=n3(this),c=g.As();this.o?a?(a=this.context.logger,o3(a,b.Yd.Xr),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.sf&&g.Vs(c,b.sf)):(a=this.context.logger,o3(a,b.Yd.Xr),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.le&&g.Vs(c,b.le)):(a=this.context.logger,o3(a,b.Yd.Xr),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.I&&g.Vs(c,this.I))};g.t(p3,e3);p3.prototype.bo=function(){e3.prototype.bo.call(this);Fwa(this)};
p3.prototype.show=function(){e3.prototype.show.call(this);var a=g.As(),b=this.annotation.data;a&&b&&(b=b.session_data)&&B2(a,[g.us(b.itct)])};
p3.prototype.hide=function(){e3.prototype.hide.call(this);var a=g.As(),b=this.annotation.data;a&&b&&(b=b.session_data)&&C2(a,[g.us(b.itct)])};g.t(q3,p3);
q3.prototype.show=function(){if(!this.isActive){p3.prototype.show.call(this);if(!this.G){g.I(this.xa(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({D:"img",X:["branding-img","iv-click-target"],P:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Wh(this.u,!1);var b=this.createElement({D:"div",X:["branding-img-container"]});b.appendChild(this.u);this.xa().appendChild(b);(b=this.annotation.zc())&&this.Ml(this.u,b,this.annotation.id,a.session_data);
Jwa(this,a);this.G=!0}g.Wh(this.xa(),!0);this.isActive=!0;this.u&&Gwa(this,this.u)}};
q3.prototype.hide=function(){this.isActive&&(p3.prototype.hide.call(this),g.Wh(this.xa(),!1),this.isActive=!1)};
q3.prototype.destroy=function(){this.o&&(this.o.dispose(),this.o=null);p3.prototype.destroy.call(this)};g.t(r3,p3);g.k=r3.prototype;g.k.show=function(){this.isActive||(p3.prototype.show.call(this),this.M||(Kwa(this),this.M=!0),g.Wh(this.xa(),!0),g.dg(function(){g.In(this.xa(),"iv-promo-inactive")},100,this),this.xa().removeAttribute("aria-hidden"),this.isActive=!0,t3(this),Lwa(this),Mwa(this,this.F))};
g.k.hide=function(){this.isActive&&(g.I(this.xa(),"iv-promo-inactive"),this.isActive=!1,this.xa().setAttribute("aria-hidden","true"))};
g.k.rq=function(a,b,c,d,e,f){return this.isCollapsed?!1:p3.prototype.rq.call(this,a,b,c,d,e,f)};
g.k.bH=function(a){this.I=!0;s3(this,500,a)};
g.k.aH=function(){this.I=!1;Nwa(this)};
g.k.TG=function(a){a.stopPropagation();this.hide()};
g.k.UG=function(a){a.stopPropagation();t3(this);this.isCollapsed=!0;g.I(this.xa(),"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();p3.prototype.destroy.call(this)};g.t(u3,g.TN);g.k=u3.prototype;g.k.cd=function(a,b){if(!Qwa(this.player.O().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.y1(b);c&&v3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(xwa(this.o,b),A2(this.player)),!0}return null};
g.k.getOptions=function(){return Qwa(this.player.O().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.qr=function(){if(this.B){var a=g.oN(this.player).getVideoContentRect(!0);g.Uh(this.B.element,a.width,a.height);g.Kh(this.B.element,a.left,a.top)}if(this.o){var b=this.player.Wk();a=this.o;b=b.width;g.J(a.F,"iv-drawer-small",426>=b);g.J(a.F,"iv-drawer-big",1280<=b)}};
g.k.jI=function(a){Rwa(this,a.state);g.T(a.state,2)&&(this.qn()&&this.EA()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Su(!1))};
g.k.load=function(){g.TN.prototype.load.call(this);Rwa(this,g.pM(this.player));this.M++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.AL,this,b,this.M),d=(0,g.x)(function(){this.F=null},this);
g.xp()&&(c=Vwa(this,c));c={format:"XML",zd:c,onError:d,We:{}};a.isPharma&&(c.We.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.O().M.get(b))&&Wwa(c,b);b=b&&(b.hp||b.gp);if(!a.So||b)a.af?Swa(this,a.af,c):(this.A=(0,g.x)(this.kI,this,c),this.player.addEventListener("videodatachange",this.A));g.FN(this.player,this.B.element,4);this.qr();(b=g.XB(a))&&axa(this,b);(b=g.YB(a))&&b.featuredChannel&&bxa(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.k.kI=function(a){var b=this.player.getVideoData();b.af&&(this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null),Swa(this,b.af,a))};
g.k.unload=function(){g.vQ(this.player.app,"annotations_module",void 0);g.Bb(this.G,function(a){a.destroy()});
this.I=null;this.o&&(this.o.destroy(),this.o=null,A2(this.player));this.N=!1;this.F&&(this.F.abort(),this.F=null);this.G={};this.u.hide();g.TN.prototype.unload.call(this);this.B.detach();this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null)};
g.k.AL=function(a,b,c){this.F=null;!Uwa(this,b,a)&&(a=g.pq(c)&&c.responseXML?c.responseXML:null)&&(v3(this,a),g.I(this.player.getRootNode(),"iv-module-loaded"))};
g.k.GC=function(a){a==this.player.getVideoData().videoId&&(this.loaded?Xwa(this):this.load())};
g.k.qn=function(){return!!this.o&&this.o.isAvailable()};
g.k.EA=function(){this.qn();return!!this.o&&this.o.C};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.qn();this.o&&(a?c?g3(this.o,c,b):g3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):h3(this.o))};
g.k.Su=function(a,b){this.player.S(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.Y=function(){this.player.O().M.unsubscribe("vast_info_card_add",this.GC,this);g.In(this.player.getRootNode(),g.fM.IV_DRAWER_OPEN);for(var a=this.R,b=0,c=a.length;b<c;b++)g.yp(a[b]);this.R.length=0;g.TN.prototype.Y.call(this)};g.dO.annotations_module=u3;g.dO.creatorendscreen=N2;})(_yt_player);
